name: gnome-characters
adopt-info: gnome-characters
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core24

layout:
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs

slots:
  # for GtkApplication registration
  gnome-characters:
    interface: dbus
    bus: session
    name: org.gnome.Characters

apps:
  gnome-characters:
    command: usr/share/org.gnome.Characters/org.gnome.Characters
    extensions: [gnome]
    plugs:
      - browser-support
      - home
    desktop: usr/share/applications/org.gnome.Characters.desktop
    common-id: org.gnome.Characters.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/org.gnome.Characters:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/gnome-platform/usr/lib:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      GI_TYPELIB_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/org.gnome.Characters/girepository-1.0:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gjs/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}

parts:
  gnome-characters:
    source: https://gitlab.gnome.org/GNOME/gnome-characters.git
    source-type: git
    source-tag: '46.0'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '47'
#     no-9x-revisions: true
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
    parse-info: [usr/share/metainfo/org.gnome.Characters.appdata.xml]
    override-pull: |
      craftctl default
      sed -i -e 's|@GJS@|/usr/bin/gjs|g' src/org.gnome.Characters.in
      sed -i.bak -e 's|=@appid@$|=${SNAP}/meta/gui/org.gnome.Characters.svg|g' data/org.gnome.Characters.desktop.in.in
      for i in $CRAFT_PROJECT_DIR/patches/*.diff; do
        patch -p1 < $i
      done
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.Characters.svg $CRAFT_PART_INSTALL/meta/gui/
      sed -i -e 's|=@bindir@/gnome-characters$|=${SNAP}/usr/share/org.gnome.Characters/org.gnome.Characters|g' data/org.gnome.Characters.desktop.in
    build-packages:
      - desktop-file-utils
      - gperf
      - libunistring-dev
      - libmozjs-115-dev
    stage-packages:
      - libmozjs-115-0
    prime:
      - -usr/bin/gnome-characters
